### ISSUE TITLE
optimize bigquery table fetch for table filters

### ISSUE THREAD

**Issue by bsushmith** [goto/guardian#113]
**Summary**
If the user has set a table filter like `resource.urn contains dataset_name`. The current bigquery provider code will get all tables in the given bigquery project and then at provider level, it will apply filter. If a project has many tables, this will take a lot of time and be a performance problem.

Ref: https://github.com/goto/guardian/pull/104/files#r1375674677

**Comment by rahmatrhd** [comment]
@bsushmith can we close this issue already?
