### ISSUE TITLE
Metadata Sources Check the difference between 2 dates

### ISSUE THREAD

**Issue by anjali9791** [goto/guardian#167]
In the response configuration for metadata sources, I want to check a field based on a particular day.  I think that is not currently supported. That particular day is x days before the current day. 
I am thinking of passing this in the param field which has the appeal and response Data.
Let me know your thoughts.
@rahmatrhd @mabdh

**Comment by rahmatrhd** [comment]
@anjali9791 we can use expr's built-in date function https://expr-lang.org/docs/language-definition#date-functions to parse, manipulate, and calculate date. just need to check if the current version that we use already support that or not.

**Comment by anjali9791** [comment]
Thanks @rahmatrhd . This worked.
