### ISSUE TITLE
get policy api exposes sensitive iam config

### ISSUE THREAD

**Issue by bsushmith** [goto/guardian#66]
### **Description**
In [Policy IAM Config](https://github.com/goto/guardian/blob/main/domain/policy.go#L292C3-L292C3), we store sensitive information like [password](https://github.com/goto/guardian/blob/main/plugins/identities/http.go#L28) and [service accounts](https://github.com/goto/guardian/blob/main/plugins/identities/http.go#L44). These are exposed through Get policy, update policy and list policy endpoints. 

Provider also has [credentials](https://github.com/goto/guardian/blob/main/domain/provider.go#L74C7-L74C7), but these are not exposed through get provider etc because get provider returns back encrypted credentials. 

We need to do a similar thing for policy API's also.

### **Additional context**
This can be achieved in multiple ways, 
**Approach 1. send encrypted creds back instead of decrypted**
Currently decryption is done at service level, need to stop it.

**Approach 2. Do not the creds itself back**
Removing it at handler layer so that the service layer code is not impacted.

**Comment by rahmatrhd** [comment]
agree with approach 2 as this is how we handle it for provider as well
