### ISSUE TITLE
bigquery provider with only resource type table inserts 0 resources to db

### ISSUE THREAD

**Issue by rahmatrhd** [goto/guardian#73]
**Description**
https://github.com/goto/guardian/blob/3bd8e74d641d3f91337520adec27903ccf61aa9c/plugins/providers/bigquery/provider.go#L159
We add table resources as child resources of a dataset, if dataset resource type is not specified, table resources are not added into the imported resources.

**To Reproduce**
1. Create bigquery provider with only one resource type: `table`
2. Run fetch resources job
3. Job done successfully but resources added is `0`

**Expected behavior**
Should insert/upsert table resources to db

**Comment by bsushmith** [comment]
tagging this - https://github.com/goto/guardian/issues/12. since it would also be resolved, if the above is done.
